### ISSUE TITLE
Is this file "jobs-manifest.json" really needed in production?

### ISSUE THREAD

**Issue by alvan** [aws-solutions/video-on-demand-on-aws-foundations#13]
I found that each job ends up writing the results to the same file "jobs-manifest.json".

Is this likely to cause conflicts when there are a large number of jobs or to overstretch the file size over time?
Is there any other solution to record the output or can I simply remove this part of the code in production?

**Comment by ameotoko** [comment]
@alvan Have you come to any conclusion about this? My app has processed over 600 jobs over the last 6 months, and `jobs-manifest.json` is over 8Mb now. Not a big deal yet, but the project will continue and expand.

**Comment by alvan** [comment]
@ameotoko 

In my practice, this file is not necessary.
My suggestion is that you can modify the relevant lambda functions based on your own needs.

**Comment by eggoynes** [comment]
Hi @alvan and @ameotoko 

Thank you for using our project, all this feedback is very helpful for us. 

The Video on Demand Foundation project is trying to be as easy as possible for customers. Customers were asking if there is a way to have a json manifest that lists all of their files processed that they can use to ingest the output video assets into their MAM (Media Asset Managment) software. Our idea was to put each jobs output information into the jobs-manifest.json file for this purpose. 

Customers running a higher volume of jobs can take a look at Video on Demand on AWS, that project uses a Dynamo DB database instead of writing video file data to a job-manifest.json file. 
https://github.com/aws-solutions/video-on-demand-on-aws
https://aws.amazon.com/solutions/implementations/video-on-demand-on-aws/


Thank you for the feedback.
